//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bluebean.UGFramework.ConfigData {
    
    
    [System.SerializableAttribute()]
    public class ConfigDataCharacter {
        
        private int m_ID;
        
        private string m_Name;
        
        private string m_LittleHeadIcon;
        
        private string m_MediumHeadIcon;
        
        private string m_BigHeadIcon;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
            set {
                this.m_Name = value;
            }
        }
        
        public string LittleHeadIcon {
            get {
                return this.m_LittleHeadIcon;
            }
            set {
                this.m_LittleHeadIcon = value;
            }
        }
        
        public string MediumHeadIcon {
            get {
                return this.m_MediumHeadIcon;
            }
            set {
                this.m_MediumHeadIcon = value;
            }
        }
        
        public string BigHeadIcon {
            get {
                return this.m_BigHeadIcon;
            }
            set {
                this.m_BigHeadIcon = value;
            }
        }
    }
}
