//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bluebean.UGFramework.ConfigData {
    
    
    [System.SerializableAttribute()]
    public class ConfigDataCamera {
        
        private int m_ID;
        
        private FixPointMath.Number m_Depth;
        
        private FixPointMath.Number m_Yoffset;
        
        private FixPointMath.Number m_Aspect;
        
        private FixPointMath.Number m_MinFieldOfView;
        
        private FixPointMath.Number m_MaxFieldOfView;
        
        private FixPointMath.Number m_DumpRatio;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public FixPointMath.Number Depth {
            get {
                return this.m_Depth;
            }
            set {
                this.m_Depth = value;
            }
        }
        
        public FixPointMath.Number Yoffset {
            get {
                return this.m_Yoffset;
            }
            set {
                this.m_Yoffset = value;
            }
        }
        
        public FixPointMath.Number Aspect {
            get {
                return this.m_Aspect;
            }
            set {
                this.m_Aspect = value;
            }
        }
        
        public FixPointMath.Number MinFieldOfView {
            get {
                return this.m_MinFieldOfView;
            }
            set {
                this.m_MinFieldOfView = value;
            }
        }
        
        public FixPointMath.Number MaxFieldOfView {
            get {
                return this.m_MaxFieldOfView;
            }
            set {
                this.m_MaxFieldOfView = value;
            }
        }
        
        public FixPointMath.Number DumpRatio {
            get {
                return this.m_DumpRatio;
            }
            set {
                this.m_DumpRatio = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataCharacter {
        
        private int m_ID;
        
        private string m_Name;
        
        private string m_LittleHeadIcon;
        
        private string m_MediumHeadIcon;
        
        private string m_BigHeadIcon;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
            set {
                this.m_Name = value;
            }
        }
        
        public string LittleHeadIcon {
            get {
                return this.m_LittleHeadIcon;
            }
            set {
                this.m_LittleHeadIcon = value;
            }
        }
        
        public string MediumHeadIcon {
            get {
                return this.m_MediumHeadIcon;
            }
            set {
                this.m_MediumHeadIcon = value;
            }
        }
        
        public string BigHeadIcon {
            get {
                return this.m_BigHeadIcon;
            }
            set {
                this.m_BigHeadIcon = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataInputDefault {
        
        private int m_ID;
        
        private int m_Up;
        
        private int m_Down;
        
        private int m_Left;
        
        private int m_Right;
        
        private int m_A;
        
        private int m_B;
        
        private int m_C;
        
        private int m_X;
        
        private int m_Y;
        
        private int m_Z;
        
        private int m_Ensure;
        
        private int m_Cancel;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public int Up {
            get {
                return this.m_Up;
            }
            set {
                this.m_Up = value;
            }
        }
        
        public int Down {
            get {
                return this.m_Down;
            }
            set {
                this.m_Down = value;
            }
        }
        
        public int Left {
            get {
                return this.m_Left;
            }
            set {
                this.m_Left = value;
            }
        }
        
        public int Right {
            get {
                return this.m_Right;
            }
            set {
                this.m_Right = value;
            }
        }
        
        public int A {
            get {
                return this.m_A;
            }
            set {
                this.m_A = value;
            }
        }
        
        public int B {
            get {
                return this.m_B;
            }
            set {
                this.m_B = value;
            }
        }
        
        public int C {
            get {
                return this.m_C;
            }
            set {
                this.m_C = value;
            }
        }
        
        public int X {
            get {
                return this.m_X;
            }
            set {
                this.m_X = value;
            }
        }
        
        public int Y {
            get {
                return this.m_Y;
            }
            set {
                this.m_Y = value;
            }
        }
        
        public int Z {
            get {
                return this.m_Z;
            }
            set {
                this.m_Z = value;
            }
        }
        
        public int Ensure {
            get {
                return this.m_Ensure;
            }
            set {
                this.m_Ensure = value;
            }
        }
        
        public int Cancel {
            get {
                return this.m_Cancel;
            }
            set {
                this.m_Cancel = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    public class ConfigDataStage {
        
        private int m_ID;
        
        private string m_Name;
        
        private int m_BorderXMin;
        
        private int m_BorderXMax;
        
        private int m_BorderYMin;
        
        private int m_BorderYMax;
        
        private FixPointMath.Vector m_P1InitPos;
        
        private FixPointMath.Vector m_P2InitPos;
        
        private int m_CameraConfigID;
        
        private string m_Prefab;
        
        public int ID {
            get {
                return this.m_ID;
            }
            set {
                this.m_ID = value;
            }
        }
        
        public string Name {
            get {
                return this.m_Name;
            }
            set {
                this.m_Name = value;
            }
        }
        
        public int BorderXMin {
            get {
                return this.m_BorderXMin;
            }
            set {
                this.m_BorderXMin = value;
            }
        }
        
        public int BorderXMax {
            get {
                return this.m_BorderXMax;
            }
            set {
                this.m_BorderXMax = value;
            }
        }
        
        public int BorderYMin {
            get {
                return this.m_BorderYMin;
            }
            set {
                this.m_BorderYMin = value;
            }
        }
        
        public int BorderYMax {
            get {
                return this.m_BorderYMax;
            }
            set {
                this.m_BorderYMax = value;
            }
        }
        
        public FixPointMath.Vector P1InitPos {
            get {
                return this.m_P1InitPos;
            }
            set {
                this.m_P1InitPos = value;
            }
        }
        
        public FixPointMath.Vector P2InitPos {
            get {
                return this.m_P2InitPos;
            }
            set {
                this.m_P2InitPos = value;
            }
        }
        
        public int CameraConfigID {
            get {
                return this.m_CameraConfigID;
            }
            set {
                this.m_CameraConfigID = value;
            }
        }
        
        public string Prefab {
            get {
                return this.m_Prefab;
            }
            set {
                this.m_Prefab = value;
            }
        }
    }
}
